<?php if ($block->isEnabled("minicart")) : ?>
<div class="stripe-payments-express-minicart">
    <div id="payment-request-button-minicart" class="payment-request-button"></div>
    <script>
        require(['domReady!', 'StripeIntegration_Payments/js/stripe_payments_express', 'Magento_Customer/js/customer-data'], function(domReady, stripeExpress, customerData)
        {
            var cart = customerData.get('cart');
            var initECE = function()
            {
                var locationDetails = {
                    location: 'minicart',
                    activeLocations: <?= $block->getActiveLocations(); // phpcs:ignore ?>,
                };
                stripeExpress.initStripeExpress(
                    '#payment-request-button-minicart',
                    <?= $block->initParams->getWalletParams(); // phpcs:ignore ?>,
                    locationDetails,
                    <?= $block->getButtonConfig(); // phpcs:ignore ?>,
                    stripeExpress.initMiniCartWidget.bind(stripeExpress)
                );
            };
            initECE();

            cart.subscribe(function ()
            {
                // Wait for Magento to commit the changes before re-initializing the ECE
                setTimeout(initECE, 500);
            });
        });
    </script>
</div>
<?php endif; ?>
