<div class="payment-flow-icon">
    <a href="<?= $block->getExternalUrl(); //phpcs:ignore ?>" target="_blank">
        <img src="<?= $block->getIconPreview(); //phpcs:ignore ?>" width="160px" />
    </a>
</div>

<p class="payment-flow-description">With the redirect payment flow, customers are redirected to <a href="<?= $block->getExternalUrl(); //phpcs:ignore ?>" target="_blank">Stripe Checkout</a> to complete their payment.</p>
