<div class="payment-flow-icon">
    <a href="<?= $block->getExternalUrl(); //phpcs:ignore ?>" target="_blank">
        <img src="<?= $block->getIconPreview(); //phpcs:ignore ?>" width="160px" />
    </a>
</div>

<p class="payment-flow-description">With the embedded payment flow, an iframe-based <a href="<?= $block->getExternalUrl(); //phpcs:ignore ?>" target="_blank">Payment Element</a> is displayed directly on your Magento checkout page.</p>
