<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @package     Geissweb_Euvat
 * @copyright   Copyright (c) 2015-2019 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Block\System\Config\Field;

class PriceDisplayType extends \Magento\Framework\View\Element\Html\Select
{
    /**
     * @var \Magento\Tax\Model\System\Config\Source\Tax\Display\Type
     */
    public $priceDisplayTypes;

    /**
     * PriceDisplayType constructor.
     *
     * @param \Magento\Framework\View\Element\Context                  $context
     * @param \Magento\Tax\Model\System\Config\Source\Tax\Display\Type $priceDisplayTypes
     * @param array                                                    $data
     */
    public function __construct(
        \Magento\Framework\View\Element\Context $context,
        \Magento\Tax\Model\System\Config\Source\Tax\Display\Type $priceDisplayTypes,
        array $data = []
    ) {
        parent::__construct($context, $data);
        $this->priceDisplayTypes = $priceDisplayTypes;
    }

    /**
     * @param string $value
     * @return $this
     */
    public function setInputName($value)
    {
        return $this->setName($value);
    }

    /**
     * Render block HTML
     *
     * @return string
     */
    public function _toHtml()
    {
        if (!$this->getOptions()) {
            $options = $this->priceDisplayTypes->toOptionArray();
            foreach ($options as $option) {
                $this->addOption($option['value'], addslashes($option['label']));
            }
        }
        return parent::_toHtml();
    }
}
