<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <div class="cusom_footer">
    <p class="cusom_footer_p">3G Mobile CCTV is a trading name of Take 2 Technology Ltd, Company reg no. 7475326</p>
    <span><?= $block->escapeHtml($block->getCopyright()) ?></span>
    <?php
echo $this->getLayout()
->createBlock('Magento\Cms\Block\Block')
->setBlockId('footer_payment')
->toHtml();
?>
</div>
</small>
