<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @package     Geissweb_Euvat
 * @copyright   Copyright (c) 2015-2019 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Model\Config\Source;

/**
 * Class EuCountries
 * @package Geissweb\Euvat\Model\Config\Source
 */
class EuCountries implements \Magento\Framework\Option\ArrayInterface
{
    /**
     * To get config values
     * @var \Geissweb\Euvat\Helper\Configuration
     */
    private $configHelper;

    /**
     * EuCountries constructor.
     *
     * @param \Geissweb\Euvat\Helper\Configuration $configHelper
     */
    public function __construct(
        \Geissweb\Euvat\Helper\Configuration $configHelper
    ) {
        $this->configHelper = $configHelper;
    }

    /**
     * Options getter
     *
     * @return array
     */
    public function toOptionArray()
    {
        return $this->configHelper->getEuCountriesOptionArray();
    }

    /**
     * Get options in "key-value" format
     *
     * @return array
     */
    public function toArray()
    {
        return $this->configHelper->getEuCountries();
    }
}
