<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @package     Geissweb_Euvat
 * @copyright   Copyright (c) 2015-2019 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Plugin\Tax;

/**
 * Class QuoteCollector
 * @package Geissweb\Euvat\Plugin\Tax
 */
class QuoteCollector
{

    /**
     * @param \Magento\Tax\Model\Sales\Total\Quote\CommonTaxCollector $subject
     * @param callable                                                $proceed
     * @param \Magento\Quote\Model\Quote\Address                      $address
     *
     * @return \Magento\Customer\Api\Data\AddressInterface
     */
    public function aroundMapAddress(
        \Magento\Tax\Model\Sales\Total\Quote\CommonTaxCollector $subject,
        callable $proceed,
        \Magento\Quote\Model\Quote\Address $address
    ) {
        /** @var \Magento\Customer\Api\Data\AddressInterface $customerAddress */
        $customerAddress = $proceed($address);

        $customerAddressId = $customerAddress->getId();
        $addressId = $address->getId();
        if (empty($customerAddressId) && !empty($addressId)) {
            $customerAddress->setId($addressId);
        }

        $customerAddressVatId = $customerAddress->getVatId();
        $addressVatId = $address->getVatId();
        if (empty($customerAddressVatId) && !empty($addressVatId)) {
            $customerAddress->setVatId($addressVatId);
        }

        $customerAddressCustomerId = $customerAddress->getCustomerId();
        $addressCustomerId = $address->getCustomerId();
        if (empty($customerAddressCustomerId) && !empty($addressCustomerId)) {
            $customerAddress->setCustomerId($addressCustomerId);
        }

        return $customerAddress;
    }
}
