<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @package     Geissweb_Euvat
 * @copyright   Copyright (c) 2015-2019 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Plugin\CheckoutLayout;

/**
 * Class CheckoutLayout
 * @package Geissweb\Euvat\Plugin
 */
class AheadworksOsc
{
    /**
     * CheckoutLayout constructor.
     *
     * @param \Geissweb\Euvat\Helper\Configuration $config
     */
    public function __construct(
        \Geissweb\Euvat\Helper\Configuration $config,
        \Geissweb\Euvat\Logger\Logger $logger
    ) {
        $this->configHelper = $config;
        $this->logger = $logger;
    }

    /**
     * @param \Aheadworks\OneStepCheckout\Block\Checkout $subject
     * @param string $jsLayout
     * @return string $jsLayout
     */
    public function afterGetJsLayout(
        \Aheadworks\OneStepCheckout\Block\Checkout $subject,
        $jsLayout
    ) {
        $jsLayout = json_decode($jsLayout, true);

        $originalLayout = [];
        if (isset($jsLayout['components']['checkout']['children']['shippingAddress']['children']
            ['shipping-address-fieldset']['children']['vat_id-field-row']['children']['vat_id'])
        ) {
            $originalLayout = $jsLayout['components']['checkout']['children']['shippingAddress']['children']
            ['shipping-address-fieldset']['children']['vat_id-field-row']['children']['vat_id'];
            $this->logger->debug("Aheadworks OriginalLayout: ".var_export($originalLayout, true));
        }

        $configParam = isset($originalLayout['config']) ? $originalLayout['config'] : [];

        $fieldLayout = [
            'label' => __('VAT Number'),
            'component' => 'Geissweb_Euvat/js/form/element/vat-number-aheadworks',
            'config' => $this->configHelper->getVatFieldConfigAheadworks($configParam, 'shippingAddress'),
            'dataScope' => 'shippingAddress.vat_id',
            'provider' => 'checkoutProvider',
            'visible' => true,
            'sortOrder' => 120,
            'validation' => $this->configHelper->getFieldValidationAtCheckout()
        ];
        $fieldLayout = array_merge($originalLayout, $fieldLayout);


        $jsLayout['components']['checkout']['children']['shippingAddress']['children']
        ['shipping-address-fieldset']['children']['vat_id-field-row']['children']['vat_id'] = $fieldLayout;

        //Add to billing address
        $billingFieldLayout = $fieldLayout;
        $billingFieldLayout['config'] = $this->configHelper->getVatFieldConfigAheadworks($configParam, 'billingAddress');
        $billingFieldLayout['dataScope'] = 'billingAddress.vat_id';
        $jsLayout['components']['checkout']['children']['paymentMethod']['children']['billingAddress']['children']
        ['billing-address-fieldset']['children']['vat_id-field-row']['children']['vat_id'] = $billingFieldLayout;

        //$this->logger->debug(var_export($jsLayout,true));
        return \Zend_Json::encode($jsLayout);
    }
}
