<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @package     Geissweb_Euvat
 * @copyright   Copyright (c) 2015-2019 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Plugin\CheckoutLayout;

use Geissweb\Euvat\Helper\Configuration;
use Geissweb\Euvat\Logger\Logger;

/**
 * Class CheckoutLayout
 * @package Geissweb\Euvat\Plugin
 */
class MageplazaOsc
{
    /**
     * @var Configuration
     */
    public $configHelper;

    /**
     * @var Logger
     */
    public $logger;

    /**
     * CheckoutLayout constructor.
     *
     * @param Configuration $config
     * @param Logger        $logger
     */
    public function __construct(
        Configuration $config,
        Logger $logger
    ) {
        $this->configHelper = $config;
        $this->logger = $logger;
    }

    /**
     * @param \Mageplaza\Osc\Block\Checkout\LayoutProcessor $subject
     * @param array $jsLayout
     * @return array $jsLayout
     */
    public function afterProcess(
        \Mageplaza\Osc\Block\Checkout\LayoutProcessor $subject,
        array $jsLayout
    ) {
        $originalLayout = [];
        if (isset($jsLayout['components']['checkout']['children']['steps']['children']['shipping-step']['children']
            ['shippingAddress']['children']['shipping-address-fieldset']['children']['vat_id'])
        ) {
            $originalLayout = $jsLayout['components']['checkout']['children']['steps']['children']['shipping-step']['children']
            ['shippingAddress']['children']['shipping-address-fieldset']['children']['vat_id'];
            $this->logger->debug("OriginalLayout: ".var_export($originalLayout, true));
        }

        $configParam = isset($originalLayout['config']) ? $originalLayout['config'] : [];
        $fieldLayout = [
            'label' => __('VAT Number'),
            'component' => 'Geissweb_Euvat/js/form/element/vat-number-mageplaza',
            'config' => $this->configHelper->getVatFieldConfigMageplaza($configParam, 'shippingAddress'),
            'dataScope' => 'shippingAddress.vat_id',
            'provider' => 'checkoutProvider',
            'visible' => true,
            //'sortOrder' => 120,
            'validation' => $this->configHelper->getFieldValidationAtCheckout()
        ];
        $fieldLayout = array_merge($originalLayout, $fieldLayout);
        $this->logger->debug("Merged Layout: ".var_export($fieldLayout, true));

        //Add field to shipping address
        $jsLayout['components']['checkout']['children']['steps']['children']['shipping-step']['children']
        ['shippingAddress']['children']['shipping-address-fieldset']['children']['vat_id'] = $fieldLayout;

        //Add to billing address
        $billingFieldLayout = $fieldLayout;
        $billingFieldLayout['config'] = $this->configHelper->getVatFieldConfigMageplaza($configParam, 'billingAddress');
        $billingFieldLayout['dataScope'] = 'billingAddress.vat_id';
        $jsLayout['components']['checkout']['children']['steps']['children']['shipping-step']['children']
        ['billingAddress']['children']['billing-address-fieldset']['children']['vat_id'] = $billingFieldLayout;

        //$this->logger->debug(var_export($jsLayout['components']['checkout']['children']['steps']['children']['shipping-step']['children']
        //['shippingAddress']['children']['shipping-address-fieldset']['children']['vat_id'],true));

        $this->logger->debug(var_export($jsLayout['components']['checkout']['children']['steps']['children']['shipping-step']['children']
        ['billingAddress']['children']['billing-address-fieldset'], true));

        return $jsLayout;
    }
}
