<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @package     Geissweb_Euvat
 * @copyright   Copyright (c) 2015-2019 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Controller\Adminhtml\Vatnumber;

use Magento\Framework\Controller\ResultFactory;
use Magento\Framework\Controller\Result\Json as JsonResult;
use Magento\Framework\Controller\Result\Raw as RawResult;
use Magento\Framework\Controller\Result\Redirect as RedirectResult;
use Magento\Framework\Exception\LocalizedException;

/**
 * Class Validation
 * @package Geissweb\Euvat\Controller\Adminhtml\Vatnumber
 */
class Validation extends \Magento\Backend\App\Action //FrontValidation
{
    /**
     * @var \Geissweb\Euvat\Helper\Configuration
     */
    public $configHelper;

    /**
     * @var \Geissweb\Euvat\Model\Validation\Vies
     */
    public $viesService;

    /**
     * @var \Magento\Backend\App\Action\Context
     */
    public $context;

    /**
     * @var \Geissweb\Euvat\Logger\Logger
     */
    public $logger;

    /**
     * @var \Geissweb\Euvat\Helper\Functions
     */
    public $functionsHelper;

    /**
     * @var \Magento\Framework\DataObjectFactory
     */
    public $dataObjectFactory;
    /**
     * @var \Geissweb\Euvat\Model\ValidationRepository
     */
    private $validationRepository;
    /**
     * @var \Geissweb\Euvat\Model\ValidationFactory
     */
    private $validationFactory;

    /**
     * Constructor
     *
     * @param \Magento\Backend\App\Action\Context        $context
     * @param \Magento\Framework\DataObjectFactory       $dataObjectFactory
     * @param \Geissweb\Euvat\Helper\Configuration       $configHelper
     * @param \Geissweb\Euvat\Helper\Functions           $functionsHelper
     * @param \Geissweb\Euvat\Model\Validation\Vies      $viesService
     * @param \Geissweb\Euvat\Model\ValidationRepository $validationRepository
     * @param \Geissweb\Euvat\Model\ValidationFactory    $validationFactory
     * @param \Geissweb\Euvat\Logger\Logger              $logger
     *
     * @internal param \Magento\Framework\Json\Helper\Data $jsonHelper
     */
    public function __construct(
        \Magento\Backend\App\Action\Context $context,
        \Magento\Framework\DataObjectFactory $dataObjectFactory,
        \Geissweb\Euvat\Helper\Configuration $configHelper,
        \Geissweb\Euvat\Helper\Functions $functionsHelper,
        \Geissweb\Euvat\Model\Validation\Vies $viesService,
        \Geissweb\Euvat\Model\ValidationRepository $validationRepository,
        \Geissweb\Euvat\Model\ValidationFactory $validationFactory,
        \Geissweb\Euvat\Logger\Logger $logger
    ) {
        parent::__construct($context);
        $this->context = $context;
        $this->dataObjectFactory = $dataObjectFactory;
        $this->configHelper = $configHelper;
        $this->functionsHelper = $functionsHelper;
        $this->viesService = $viesService;
        $this->validationRepository = $validationRepository;
        $this->validationFactory = $validationFactory;
        $this->logger = $logger;
    }

    /**
     * Execute VAT number validation
     * @return JsonResult|RawResult|RedirectResult
     */
    public function execute()
    {
        $isSalesOrderValidation = false;
        $countryParamFromSalesValidation = '';
        $response = [
            'errors' => true,
            'message' => ''
        ];

        /** @var \Magento\Framework\Controller\Result\Raw $resultRaw */
        $resultRaw = $this->resultFactory->create(ResultFactory::TYPE_RAW);
        if ($this->getRequest()->getMethod() !== 'POST'
            || !$this->getRequest()->isXmlHttpRequest()
            || !$this->_formKeyValidator->validate($this->getRequest())
        ) {
            return $resultRaw->setHttpResponseCode(400);
        }

        switch ($this->configHelper->getValidationService()) {
            case \Geissweb\Euvat\Model\System\Config\Source\Interfaces::BZST:
                $service = null;
                break;
            case \Geissweb\Euvat\Model\System\Config\Source\Interfaces::VIES:
            default:
                $service = $this->viesService;
                break;
        }

        $vatNumber = $this->getRequest()->getPost('vat_number');
        $vatNumberFromSalesValidation = $this->getRequest()->getPost('vat');
        if (empty($vatNumber) && !empty($vatNumberFromSalesValidation)) {
            $isSalesOrderValidation = true;
            $vatNumber = $vatNumberFromSalesValidation;
            $countryParamFromSalesValidation = $this->getRequest()->getPost('country');
        }
        $vatCc = substr($vatNumber, 0, 2);
        $vatNumberWithoutCountry = str_replace($vatCc, '', $vatNumber);


        if ($service && $service->isOnline()) {

            try {
                // Set service params
                $service->setParam('countryCode', $vatCc);
                $service->setParam('vatNumber', $vatNumberWithoutCountry);
                $service->connect();
                $service->validate();
                /** @var \Geissweb\Euvat\Api\Data\ValidationResultInterface $response */
                $response = $service->getResult();

                if ($isSalesOrderValidation) {
                    $address = $this->dataObjectFactory->create();
                    $address->setCountryId($countryParamFromSalesValidation);

                    /** @var \Geissweb\Euvat\Api\Data\ValidationInterface $validation */
                    $vatValidation = $this->validationRepository->getByVatId($vatNumber);
                    if (!$vatValidation) {
                        $vatValidation = $this->validationFactory->create();
                    }
                    if ($response->getVatTraderName() == null) {
                        $response->setVatTraderName("");
                    }
                    if ($response->getVatTraderAddress() == null) {
                        $response->setVatTraderAddress("");
                    }
                    $response = [
                        'group' => $this->functionsHelper->getCustomerGroup($address, $vatValidation),
                        'valid' => $response->getVatIsValid(),
                        'success' => $response->getVatRequestSuccess(),
                        'trader_name' => $response->getVatTraderName(),
                        'trader_address' => $response->getVatTraderAddress()
                    ];
                }

            } catch (LocalizedException $e) {
                if ($this->configHelper->isOfflineValidationEnabled()
                   && $service->isSyntaxValid($vatNumberWithoutCountry, $vatCc)
                ) { //Todo
                    $response = $service->getOfflineResult();
                }
                $this->logger->critical($e);
            }

        }

        return $this->resultFactory->create(ResultFactory::TYPE_JSON)->setData($response);
    }
}
