<h4>
    <span class="stripe-method-title"><?= __('Stripe - Customer request for subscription update'); //phpcs:ignore ?></span>
</h4>

<table class="admin__table-secondary order-information-table stripe payment-info">
  <tbody>

    <?php if ($block->getOriginalSubscriptionOrderIncrementId()): ?>
    <tr>
        <th><?= __('Original order number'); //phpcs:ignore ?></th>
        <td class="stripe-original-order">
            <a href="<?= $block->getSubscriptionOrderUrl($block->getOriginalSubscriptionOrderIncrementId()); //phpcs:ignore ?>" target="_blank">
                #<?= $block->getOriginalSubscriptionOrderIncrementId(); //phpcs:ignore ?>
            </a>
        </td>
    </tr>
    <?php endif; ?>

    <?php if (!empty($block->getFormattedAmount())): ?>
    <tr>
        <th><?= __('Amount'); //phpcs:ignore ?></th>
        <td class="stripe-amount">
            <strong>
                <?php if ($block->isMultiShipping()): ?>
                    <?= $block->getFormattedMultishippingAmount(); //phpcs:ignore ?>
                <?php else: ?>
                    <?= $block->getFormattedAmount(); //phpcs:ignore ?>
                <?php endif; ?>
            </strong>
        </td>
    </tr>
    <?php endif; ?>

    <?php if (!empty($block->getFormattedSubscriptionAmount())): ?>
    <tr>
        <th><?= __('Subscription amount'); //phpcs:ignore ?></th>
        <td class="stripe-subscription-amount">
            <?= $block->getFormattedSubscriptionAmount(); //phpcs:ignore ?>
        </td>
    </tr>
    <?php endif; ?>

    <?php if (!empty($block->getSubscriptionStatus())): ?>
    <tr>
        <th><?= __('Subscription status'); //phpcs:ignore ?></th>
        <td class="stripe-subscription-status">
            <span class="stripe-subscription-status-<?= $block->getSubscriptionStatus(); //phpcs:ignore ?>">
                <?= $block->getSubscriptionStatusName(); //phpcs:ignore ?>
            </span>
        </td>
    </tr>
    <?php endif; ?>

    <?php if (!empty($block->getRiskScore())): ?>
    <tr>
        <th><?= __('Risk evaluation'); //phpcs:ignore ?></th>
        <td class="stripe-payment-risk-<?= $block->getRiskLevelCode(); //phpcs:ignore ?>">
            <span class="stripe-payment-risk-score <?= ucfirst($block->getRiskScore()); //phpcs:ignore ?>">
                <span class="score-value">
                    <?= ucfirst($block->getRiskScore()); //phpcs:ignore ?>
                </span>
            </span>
            <span class="stripe-payment-risk-level"><?= ucfirst($block->getRiskEvaluation()); //phpcs:ignore ?></span>
        </td>
    </tr>
    <?php endif; ?>
    <?php if ($block->getPaymentId()): ?>
    <tr>
        <th><?= __('Payment'); //phpcs:ignore ?></th>
        <td class="payment">
            <a href="https://dashboard.stripe.com/<?= $block->getMode(); //phpcs:ignore ?>payments/<?= $block->getPaymentId(); //phpcs:ignore ?>" target="_blank" rel="noopener noreferrer">View in Stripe</a>
        </td>
    </tr>
    <?php endif; ?>
    <?php if ($block->getSubscription()): ?>
    <tr>
        <th><?= __('Subscription'); //phpcs:ignore ?></th>
        <td class="subscription">
            <a href="https://dashboard.stripe.com/<?= $block->getMode(); //phpcs:ignore ?>subscriptions/<?= $block->getSubscription()->id; //phpcs:ignore ?>" target="_blank" rel="noopener noreferrer">View in Stripe</a>
        </td>
    </tr>
    <?php endif; ?>
    <?php if ($block->getCustomerId()): ?>
    <tr>
        <th><?= __('Customer'); //phpcs:ignore ?></th>
        <td class="customer">
            <a href="https://dashboard.stripe.com/<?= $block->getMode(); //phpcs:ignore ?>customers/<?= $block->getCustomerId(); //phpcs:ignore ?>" target="_blank" rel="noopener noreferrer">View in Stripe</a>
        </td>
    </tr>
    <?php endif; ?>
    <?php if ($block->getVoucherLink()): ?>
    <tr>
        <th><?= __('Voucher'); //phpcs:ignore ?></th>
        <td class="customer">
            <a href="<?= $block->getVoucherLink(); //phpcs:ignore ?>" target="_blank" rel="noopener noreferrer"><?= __("View voucher"); //phpcs:ignore ?></a>
        </td>
    </tr>
    <?php endif; ?>

    </tbody>
</table>
