<?php if (!empty($block->getPaymentMethodCode())): ?>
<div style="line-height: 40px">
    <?php if ($block->getPaymentMethodIconUrl()): ?>
        <img height="24px" style="max-height: 24px" src="<?= $block->getPaymentMethodIconUrl("png"); //phpcs:ignore ?>">
    <?php endif; ?>
    <?php if ($block->getPaymentMethodName()): ?>
        <span style="display: inline-block; position: relative; top: -7px; left: 5px;"><?= $block->getPaymentMethodName(true); //phpcs:ignore ?></span>
    <?php endif; ?>
</div>
<?php endif; ?>

<?php if ($block->getVoucherLink()): ?>
<div style="line-height: 40px">
    <span><a href="<?= $block->getVoucherLink(); //phpcs:ignore ?>" target="_blank" rel="noopener noreferrer"><?= __("View voucher"); //phpcs:ignore ?></a></span>
</div>
<?php endif; ?>

<?php if ($block->getPaymentMethodVerificationUrl()): ?>
<div style="padding: 0.5em 1.5em; background-color: #fffbbb; border: 1px solid #999;">
    <span>Your payment method is pending verification. <a href="<?= $block->getPaymentMethodVerificationUrl(); //phpcs:ignore ?>" target="_blank" rel="noopener noreferrer"><?= __("Click here to verify your payment method"); //phpcs:ignore ?></a>.</span>
</div>
<?php endif; ?>