<?php
$canceledSubscriptions = $block->getCanceledSubscriptions();
if (empty($canceledSubscriptions))
  return;
?>

<tr>
  <td colspan="3" style="border-top: 0">
    <h3><?= __("Canceled Subscriptions"); //phpcs:ignore ?></h3>
  </td>
</tr>
<?php foreach ($canceledSubscriptions as $subscription) : ?>
  <?php
  /** @var \StripeIntegration\Payments\Model\Stripe\Subscription $stripeSubscriptionModel */
  $stripeSubscriptionModel = $block->getSubscriptionModel($subscription);
  ?>
  <tr class="<?= $subscription->id; //phpcs:ignore ?>">
    <td data-th="Order #" class="col order">
      <a href="viewOrder/<?= $subscription->metadata["Order #"]; //phpcs:ignore ?>">
        <?= $subscription->metadata["Order #"]; //phpcs:ignore ?>
      </a>
    </td>
    <td data-th="<?= __("Subscription"); //phpcs:ignore ?>" class="col id">
      <div class="subscription-name">
        <?= $block->getSubscriptionName($subscription); //phpcs:ignore ?>
      </div>
      <div class="billed">
        <?= $stripeSubscriptionModel->getFormattedBilling(); //phpcs:ignore ?>
      </div>
      <div class="<?= $subscription->id; //phpcs:ignore ?> payment-method stripe-subscription-edit">
        <div class="static section">
          <div class="details stripe-payments">
            <?php $paymentMethod = $block->getSubscriptionDefaultPaymentMethod($subscription); ?>
            <?php if ($paymentMethod) : ?>
              <img class="icon" src="<?= $paymentMethod['icon']; //phpcs:ignore ?>" alt="<?= $paymentMethod['label']; //phpcs:ignore ?>">
              <span class="label"><?= $paymentMethod['label']; //phpcs:ignore ?></span>
              <?php if (!empty($paymentMethod['exp_month'])) : ?>
                <span class="exp">
                  <?= $paymentMethod['exp_month']; //phpcs:ignore ?>/<?= $paymentMethod['exp_year']; //phpcs:ignore ?>
                </span>
              <?php endif; ?>
            <?php else : ?>
              <?= __("No payment method."); //phpcs:ignore ?>
            <?php endif; ?>
          </div>
        </div>
      </div>
    </td>
    <td data-th="Actions" class="col">
      <div class="primary">
        <button type="button" onclick="location.href='<?= $block->getUrl('stripe/customer/subscriptions/reactivate/' . $subscription->id); //phpcs:ignore ?>';" class="action" title="<?= __("Reactivate"); //phpcs:ignore ?>">
          <span><?= __("Reactivate"); //phpcs:ignore ?></span>
        </button>
      </div>
    </td>
  </tr>
<?php endforeach; ?>