<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Contact\Block\ContactForm $block */
?>
<div class="contact-us-section">
    <div class="contact-us-section-1">
        <div class="contact-content">
                <ul class="address-info">
                    <li class="add-icon">3G Mobile CCTV<br>Take 2 Technology Ltd, Isnage Farm,<br> Bentley, Hampshire, GU10 5LX, UK</li>
                    <li class="email-icon">Email: <a title="Send Email" href="mailto:sales@3gmobilecctv.com">sales@3gmobilecctv.com</a></li>
                    <li class="phone-icon">UK : 0207 096 8420</li>
                    <li class="phone-icon">Intl. : +44 207 096 8420</li>
                    <li class="phone-icon">US : (646) 290 8036</li>
                </ul>
        </div> 
</div>
<div class="contact-us-section-2">
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Write Us')) ?></span></legend><br />
        <div class="field note no-label"><?= $block->escapeHtml(__('Jot us a note and we’ll get back to you as quickly as possible.')) ?></div>
        <div class="group-first-input">
        <div class="field name required">
            <!--<label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>-->
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('name') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}" placeholder="Name*"/>
            </div>
        </div>
        <div class="field email required">
           <!-- <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>-->
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('email') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" placeholder="Email*"/>
            </div>
        </div>
        </div>
        <div class="field telephone">
           <!-- <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>-->
            <div class="control">
                <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('telephone')) ?>" class="input-text 3g-phone" type="text" placeholder="Phon Number*"/>
            </div>
        </div>
        <div class="field comment required">
           <!-- <label class="label" for="comment"><span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span></label>-->
            <div class="control">
                <textarea placeholder="'What’s on your mind?" name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('comment')) ?></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
</div>
</div>
